--[[
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
]]

-- The current number in the fibonacci sequence we are at
fib = 1
-- The previous number in the sequence
prev = 1
-- The sum of all numbers meeting our criteria so far
sum = 0
-- The limit of our search
limit = 4000000

-- While we are below our limit
while fib < limit do
	-- If the number is even, add it to the sum
	if fib % 2 == 0 then
		sum = sum + fib
	end
	-- Then calculate the value of the next term. Use a temporary variable to swap our current value into the "prev" variable
	local temp = fib
	fib = fib + prev
	prev = temp
end

-- Print the final result
io.write(string.format("The sum of all even numbers below %.0f in the fibonacci sequence is ", limit), sum)